// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type School struct {
	ID        string `json:"id" db:"id"`
	CreatedAt string `json:"created_at" db:"created_at"`
	UpdatedAt string `json:"updated_at" db:"updated_at"`
	Name      string `json:"name" db:"name"`
}
